version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - TOGETHER_API_KEY=66080cd8c8a367dc181009a94afd1fa8c206d3b9926f2c51f500d1a9f8d51502
      - LLM_MODEL=meta-llama/Llama-3.3-70B-Instruct-Turbo-Free
      - PYTHONPATH=/codes
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    #volumes:
    #  - redis_data:/data

  # Frontend básico (Streamlit para prototipado rápido - opcional)
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "8501:8501"
  #   volumes:
  #     - ./frontend:/app
  #   depends_on:
  #     - backend
#volumes:
#  redis_data:
